export const types = {
  SET_GAME_STARTED : 'SET_GAME_STARTED',
  SET_GAME_FINISHED : 'SET_GAME_FINISHED',
  SET_INSTRUCTIONS_EXPANDED : 'SET_INSTRUCTIONS_EXPANDED',
  SET_INSTRUCTIONS_COLLAPSED : "SET_INSTRUCTIONS_COLLAPSED",
  FETCH_DECK : 'FETCH_DECK',
  FETCH_DECK_ERROR: 'FETCH_DECK_ERROR'
}